### ISSUE TITLE
Possible Debounce Issue

### ISSUE THREAD

**Issue by Chirishman** [AdaCore/SPARK-to-C_Tetris_Demo#1]
Rapid lateral presses are sometimes read as a single press and input sometimes flips a piece twice on a single button press.

**Comment by Fabien-Chouteau** [comment]
Hi @Chirishman,

You right, the button handling should be improved. I will keep this as an enhancement request.

Thanks for your feedback,

**Comment by Fabien-Chouteau** [comment]
I will not go back to this project so I am closing this issue.
